import { RiExchangeLine, RiMegaphoneLine, RiCoinsLine, RiContactsLine, RiCoupon2Line, RiExchangeDollarFill, RiHomeLine, RiImageLine, RiListUnordered, RiMailLine, RiPagesLine, RiQuestionnaireLine, RiSettings3Line, RiStore2Line, RiStore3Line, RiTruckLine, RiWalletLine, RiWindowLine, RiVideoLine, RiPriceTag3Line, RiGroupLine } from "react-icons/ri";

const MENUITEMS = [
  {
    title: "Dashboard",
    displayTitle: "Dashboard",
    icon: <RiHomeLine />,
    path: "/dashboard",
    type: "link",
  },
  {
    title: "Users",
    displayTitle: "Users",
    icon: <RiContactsLine />,
    type: "sub",
    children: [
      { title: "AddUser", path: "/user/create", displayTitle: "AddUser", permission: ["user.create"] },
      { title: "AllUsers", path: "/user", displayTitle: "AllUsers", permission: ["user.index"] },
      { title: "Role", path: "/role", displayTitle: "Role", permission: ["role.index"] },
    ],
  },
  {
    title: "Products",
    displayTitle: "Products",
    icon: <RiStore3Line />,
    type: "sub",
    children: [
      { title: "AddProduct", path: "/product/create", displayTitle: "Add Product", permission: ["product.create"] },
      { title: "AllProducts", path: "/product", displayTitle: "All Product", badgeType: "badge bg-warning text-dark ml-3", badgeValue: 0, permission: ["product.create"] },
      { title: "Attributes", path: "/attribute", displayTitle: "All Attributes", permission: ["attribute.index", "attribute.create"] },
      { title: "Categories", path: "/category", displayTitle: "Categories", permission: ["category.index"] },
      { title: "Tags", path: "/tag", displayTitle: "All Tag", permission: ["tag.index", "tag.create"] },
      { title: "Brands", path: "/brand", displayTitle: "Brand", permission: ["brand.index", "brand.create"] },

    ],
  },
  {
    title: "Stores",
    displayTitle: "Store",
    icon: <RiStore2Line />,
    type: "sub",
    children: [

      { title: "AllStores", path: "/store", displayTitle: "All Stores", badgeType: "badge bg-warning text-dark ml-3", badgeValue: 0, permission: ["store.index"] },
      { title: "Wallet", path: "/vendor_wallet", displayTitle: "Wallets", permission: ["vendor_wallet.index"] },
    
      { title: "Withdrawal", displayTitle: "Withdrawal", path: "/withdraw_request", badgeType: "badge bg-warning text-dark ml-3", badgeValue: 0, permission: ["withdraw_request.index"] },
    ],
  },
  {
    title: "Orders",
    displayTitle: "Orders",
    icon: <RiListUnordered />,
    type: "sub",
    children: [
      { title: "AllOrders", path: "/order", displayTitle: "All Orders", permission: ["order.index"] },
      { title: "CreateOrder", path: "/order/create", displayTitle: "Create Order", permission: ["order.create"] },
    ],
  },
  {
    title: "Media",
    displayTitle: "Media",
    icon: <RiImageLine />,
    path: "/attachment",
    permission: ["attachment.index", "attachment.create"],
    type: "link",
  },
  {
    title: "Stories",
    displayTitle: "Stories",
    icon: <RiVideoLine />,
    type: "sub",
    children: [
      { title: "AddStory", path: "/story/create", displayTitle: "Add Story" },
      { title: "AllStories", path: "/story", displayTitle: "All Stories" },
    ],
  },
  {
    title: "Pages",
    displayTitle: "Pages",
    icon: <RiPagesLine />,
    path: "/page",
    permission: ["page.index"],
    type: "link",
  },
  {
    title: "Shipping",
    displayTitle: "Shipping",
    icon: <RiTruckLine />,
    path: "/shipping",
    permission: ["shipping.index"],
    type: "link",
  },
  {
    title: "AramexStatusMapping",
    displayTitle: "Aramex Status Mapping",
    icon: <RiTruckLine />,
    path: "/aramex-status-mapping",
    permission: ["aramex.index"],
    type: "link",
  },
  {
    title: "Coupons",
    displayTitle: "Coupons",
    icon: <RiCoupon2Line />,
    path: "/coupon",
    permission: ["coupon.index"],
    type: "link",
  },
  {
    title: "Offers",
    displayTitle: "Offers",
    icon: <RiMegaphoneLine />,
    type: "sub",
    permission: ["discount-rule.index", "discount-rule.create", "offers.index", "promo-group.index"],
    children: [
      {
        title: "DiscountRules",
        displayTitle: "Discount Rules",
        icon: <RiPriceTag3Line />,
        type: "sub",
        permission: ["discount-rule.index", "discount-rule.create"],
        children: [
          { title: "AllDiscountRules", path: "/offers/discount-rules/all", displayTitle: "All Rules", permission: ["discount-rule.index"] },
          { title: "AddDiscountRule", path: "/offers/discount-rules/add", displayTitle: "Add Rule", permission: ["discount-rule.create"] },
          { title: "DiscountReports", path: "/offers/discount-rules/reports", displayTitle: "Reports & Statistics", permission: ["discount-rule.index"] },
        ],
      },
      {
        title: "PromoGroups",
        displayTitle: "Promo Groups",
        icon: <RiGroupLine />,
        type: "sub",
        permission: ["promo-group.index", "promo-group.create"],
        children: [
          { title: "AllPromoGroups", path: "/promo-group", displayTitle: "All Promo Groups", permission: ["promo-group.index"] },
          { title: "AddPromoGroup", path: "/promo-group/create", displayTitle: "Add Promo Group", permission: ["promo-group.create"] },
        ],
      },
      { title: "GiftBoxOffer", path: "/offers/gift-box", displayTitle: "Gift Box", permission: ["offers.index"] },
    ],
  },
  {
    title: "Points",
    displayTitle: "Point",
    icon: <RiCoinsLine />,
    path: "/point",
    permission: ["point.index"],
    type: "link",
  },
  {
    title: "Wallet",
    displayTitle: "Wallet",
    icon: <RiWalletLine />,
    path: "/wallet",
    permission: ["wallet.index"],
    type: "link",
  },
  {
    title: "Refund",
    displayTitle: "Refund",
    icon: <RiExchangeDollarFill />,
    path: "/refund",
    permission: ["refund.index"],
    badgeType: "badge bg-warning text-dark ml-3",
    badgeValue: 0,
    type: "link",
  },
    {
    title: "Exchange",
    displayTitle: "Exchange",
    icon: <RiExchangeLine  />,
    path: "/exchange",
    permission: ["exchange.index"],
    badgeType: "badge bg-warning text-dark ml-3",
    badgeValue: 0,
    type: "link",
  },
  
  {
    title: "FAQ's",
    displayTitle: "FAQ's",
    icon: <RiQuestionnaireLine />,
    path: "/faq",
    permission: ["faq.index"],
    type: "link",
  },
  {
    title: "StoreFront",
    displayTitle: "Store Front",
    icon: <RiWindowLine />,
    type: "sub",
    children: [
      { title: "ThemeOptions", path: "/theme_option", displayTitle: "Theme Option", permission: ["theme_option.index"] },
      { title: "Menu", path: "/menu", displayTitle: "Menu", permission: ["menu.index"] },
    ],
  },
  {
    title: "Settings",
    displayTitle: "Settings",
    icon: <RiSettings3Line />,
    path: "/setting",
    permission: ["setting.index"],
    type: "link",
  },
  {
    title: "SubscriptionEmails",
    displayTitle: "Subscription Emails",
    icon: <RiMailLine />,
    path: "/subscription",
    permission: ["setting.index"],
    type: "link",
  },
];

export default MENUITEMS;
